"""Add email and price to Booking

Revision ID: 3cf29cbc7b61
Revises: 4b337f7f5aba
Create Date: 2025-11-15 16:23:02.724728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf29cbc7b61'
down_revision = '4b337f7f5aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
